spring:
  application:
    name: payment
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/payment_db}
    username: ${SPRING_DATASOURCE_USERNAME:payment}
    password: ${SPRING_DATASOURCE_PASSWORD:payment}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: ${SERVER_PORT:8083}
